---
title: "Backlog"
author: "Pascal Bellerose"
date: "August 9, 2017"
output: 
  html_document:
    fig_width: 12
    fig_height: 4
params:
  user: ""
  pwd: ""
  shop: "SINST"
  trade: "MECA"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# ---- init ----
options(java.parameters = "-Xmx8G")
library(RODBC)
library(RJDBC)
library(dplyr)
library(data.table)
library(readr)
library(stringr)
library(manipulate)
library(ggplot2)
library(lubridate)
library(GGally)
library(MASS)
library(tidyverse)
library(readxl)
library(caret)
library(Hmisc)
```

# BACKLOG  

```{r backlog, cache=TRUE, include=FALSE}
  backlog = read_xlsx('Backlog.xlsx', col_names = TRUE, range='A2:F182')
  backlog$period = factor(paste(backlog$ANNEE, str_pad(backlog$SEM, 2, 'left', '0'), sep=''))
  periods = unique(backlog$period)
  backlog = arrange(backlog, ANNEE, SEM)
```

***  
  
### Régressif
Création d'un backlog théorique basé sur l'historique des ajouts et fermetures de BT.  

```{r WODBacklog_CustomFilter, cache=TRUE}
# ---- WOD2LoadFromFile
  colcls = load('WOD2Tidy_colcls.RData')
  
  WOD3 = fread("WOD2Tidy.csv", 
              header=TRUE, 
              colClasses = colcls,
              encoding='UTF-8')  
```

```{r WODBacklog_Tidy}
  # Summarise work order issued
  WODCRT = group_by(WOD3,
                    as.numeric(as.character(CRTYR)), 
                    as.numeric(as.character(CRTMTH)), 
                    as.numeric(as.character(CRTWK)))
  WODCRT = as.data.frame(summarise(WODCRT, nIssued=sum(!BODTEN==0)))
  colnames(WODCRT) = c("YR","MTH","WK","nIssued")
  WODCRT$period = paste(WODCRT$YR, 
                        str_pad(WODCRT$MTH, 2, 'left', '0'), 
                        str_pad(WODCRT$WK,2 , 'left', '0'), 
                        sep='-')
  
  # Summarise work orders closed
  WODCLS = group_by(WOD3, 
                    as.numeric(as.character(CLSYR)), 
                    as.numeric(as.character(CLSMTH)), 
                    as.numeric(as.character(CLSWK)))
  WODCLS = as.data.frame(summarise(WODCLS, nClosed=sum(!BODTAC==0)))
  colnames(WODCLS) = c("YR","MTH","WK","nClosed")
  WODCLS$period = paste(WODCLS$YR, 
                        str_pad(WODCLS$MTH, 2, 'left', '0'), 
                        str_pad(WODCLS$WK, 2, 'left', '0'), 
                        sep='-')
  
  # Join results together
  WOD3 = full_join(WODCRT, WODCLS, by=c("period","YR","MTH","WK"))
  WOD3$nClosed[is.na(WOD3$nClosed)] = 0
  WOD3$nIssued[is.na(WOD3$nIssued)] = 0
  WOD3 = WOD3[!is.na(WOD3$YR),]
  WOD3$delta = as.numeric(WOD3$nIssued - WOD3$nClosed)
  WOD3 = arrange(WOD3, YR, WK)
  WOD3$delta = c(as.numeric(arrange(backlog, 
                                    desc(ANNEE), 
                                    desc(SEM))[1,4] - sum(WOD3$delta) + WOD3$delta[1]), 
                 WOD3$delta[2:length(WOD3$delta)])
  WOD3$backlog = cumsum(WOD3$delta)
```

```{r WOD3BacklogPlot_CountByWeek, dependson="WODBacklog_CustomFilter"}

  ##gdf = left_join(gdf, gdfERR, by=c('YR'='YEAR','WK'='WEEKNO'))
  gdf = arrange(WOD3[WOD3$YR >= min(backlog$ANNEE),], YR,WK)
  g1 = ggplot(data=gdf, aes(c(1:length(gdf$backlog)), backlog))
  g1 = g1 + geom_point()
  g1 = g1 + stat_smooth(method='loess', span=0.125)
  g1 = g1 + scale_x_continuous(name="Années", 
                               breaks=cumsum(c(1,table(gdf$YR)[1:3])), 
                               labels=unique(gdf$YR))
  g1 = g1 + geom_vline(xintercept = grep('2014-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2015-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2016-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2017-01-01',gdf$period), linetype=2)
  g1
  
    ##gdf = left_join(gdf, gdfERR, by=c('YR'='YEAR','WK'='WEEKNO'))

  g1 = ggplot(data=gdf, aes(c(1:length(gdf$nIssued)), nIssued))
  g1 = g1 + geom_point()
  g1 = g1 + stat_smooth(method='loess', span=0.125)
  g1 = g1 + scale_x_continuous(name="Années", 
                               breaks=cumsum(c(1,table(gdf$YR)[1:3])), 
                               labels=unique(gdf$YR))
  g1 = g1 + geom_vline(xintercept = grep('2014-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2015-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2016-01-01',gdf$period), linetype=2)
  g1 = g1 + geom_vline(xintercept = grep('2017-01-01',gdf$period), linetype=2)
  g1
  
```


